# Generated by Django 5.1.15 on 2026-01-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_user_reports'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingreport',
            new_name='reports_lis_status_f8620b_idx',
            old_name='rpt_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='listingreport',
            new_name='reports_lis_listing_2c298b_idx',
            old_name='rpt_listing_status_idx',
        ),
        migrations.RenameIndex(
            model_name='listingreport',
            new_name='reports_lis_reporte_b3778b_idx',
            old_name='rpt_reporter_created_idx',
        ),
        migrations.RenameIndex(
            model_name='listingreportevent',
            new_name='reports_lis_report__797d81_idx',
            old_name='rpt_event_report_created_idx',
        ),
        migrations.RenameIndex(
            model_name='listingreportevent',
            new_name='reports_lis_to_stat_178f9d_idx',
            old_name='rpt_event_to_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userreport',
            new_name='reports_use_status_9c690b_idx',
            old_name='ur_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userreport',
            new_name='reports_use_reporte_5be835_idx',
            old_name='ur_reported_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userreport',
            new_name='reports_use_reporte_b70008_idx',
            old_name='ur_reporter_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userreportevent',
            new_name='reports_use_report__25ae0a_idx',
            old_name='ure_report_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userreportevent',
            new_name='reports_use_to_stat_827efc_idx',
            old_name='ure_to_status_created_idx',
        ),
        migrations.AlterField(
            model_name='listingreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam'), ('prohibited', 'Prohibited'), ('duplicate', 'Duplicate'), ('other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam'), ('prohibited', 'Prohibited'), ('duplicate', 'Duplicate'), ('other', 'Other')], max_length=40),
        ),
    ]
