# Generated by hand: add Profile model
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0018_admin_seed_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(blank=True, max_length=80)),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to=lambda instance, filename: f"profiles/{instance.user_id}/avatars/{filename}")),
                ("cover", models.ImageField(blank=True, null=True, upload_to=lambda instance, filename: f"profiles/{instance.user_id}/covers/{filename}")),
                ("social_links", models.JSONField(blank=True, default=list)),
                ("seller_rating", models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ("listings_count", models.IntegerField(default=0)),
                ("followers_count", models.IntegerField(default=0)),
                ("verification_flags", models.JSONField(blank=True, default=dict)),
                ("privacy_settings", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "governorate",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.governorate",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.city",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.neighborhood",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="market_profile", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["display_name"], name="market_profile_display_name_idx")],
            },
        ),
    ]