# Generated by Copilot on 2026-01-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0022_add_cover_medium"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="market.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("querystring", models.TextField(blank=True, default="")),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_result_count", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="listingfavorite",
            constraint=models.UniqueConstraint(fields=("user", "listing"), name="uq_favorite_user_listing"),
        ),
        migrations.AddIndex(
            model_name="listingfavorite",
            index=models.Index(fields=["user", "created_at"], name="market_listi_user_id_7d6a44_idx"),
        ),
        migrations.AddIndex(
            model_name="listingfavorite",
            index=models.Index(fields=["listing", "created_at"], name="market_listi_listing__3d2b4e_idx"),
        ),
        migrations.AddConstraint(
            model_name="savedsearch",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="uq_savedsearch_user_name"),
        ),
        migrations.AddIndex(
            model_name="savedsearch",
            index=models.Index(fields=["user", "created_at"], name="market_saved_user_id_5e1a60_idx"),
        ),
    ]
