# Generated by Copilot on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_userblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatethread",
            name="buyer_last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privatethread",
            name="seller_last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
