# Generated by Copilot on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_thread_read_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicquestion",
            name="is_shadowed",
            field=models.BooleanField(default=False, db_index=True),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="is_shadowed",
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
